services:
  tradingdb:
    image: mysql:8.4
    container_name: tradingdb
    environment:
      MYSQL_ROOT_PASSWORD: pass@123
      MYSQL_DATABASE: tradingdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
volumes:
  db_data:
networks:
  mysql_network:
